CAMLPKGS := -package freespec-exec

install-extra::
	ocamlfind install freespec-stdlib-debug META src/stdlib_debug_plugin.*

uninstall::
	ocamlfind remove freespec-stdlib-debug

merlin-hook::
	echo 'PKG freespec-exec' >> .merlin