CAMLPKGS := -package freespec-exec

install-extra::
	ocamlfind install freespec-stdlib-console META src/stdlib_console_plugin.*

uninstall::
	ocamlfind remove freespec-stdlib-console

merlin-hook::
	echo 'PKG freespec-exec' >> .merlin